### ISSUE TITLE
"Allowed Memory size exhausted" when adding larger files to a ZipArchive

### ISSUE THREAD

**Issue by remipelhate** [thephpleague/flysystem-ziparchive#11]
I'm not quite sure this should be listed as an issue for this repo specifically (as I presume it's rather an issue with PHP's ZipArchive itself), however I do wonder if you could help me out.

I'm working on a project where we allow users to download all files of a (app) specific type as a zip. I stripped down/simplified the code to a bare minimum, which looks like this:
```php
namespace App\Filesystem;

use League\Flysystem\Filesystem as LeagueFilesystem;

class Filesystem extends LeagueFilesystem
{
    /**
     * Copies a file from one system to another.
     *
     * @param string $source
     * @param string $pathname
     * @return bool
     */
    public function transfer(FilesystemInterface $destination, $source, $pathname = null)
    {
        if (! $this->has($source)) {
            return false;
        }

        if ($pathname === null) {
            $pathname = $source;
        }

        $stream = $this->readStream($source);

        if (! is_resource($stream)) {
            return false;
        }

        $result = $destination->writeStream($pathname, $stream);

        // If the file is still open, close it.
        if (is_resource($stream)) {
            fclose($stream);
        }

        return (bool) $result;
    }
}
```
```php
use App\Filesystem\Filesystem;
use League\Flysystem\Adapter\Local;
use League\Flysystem\ZipArchive\ZipArchiveAdapter;

$pathname = storage_path('tmp').'/some-random-name.zip';
$local = new Filesystem(new Local());
$zip = new Filesystem(new ZipArchiveAdapter($pathname), compact('pathname'));

foreach ($riders as $rider) {
    $local->transfer($zip, $rider->getFilename(), Util::uniqueFilename($zip, $pathname));
}

$zip->close();
```

So, basically, we transfer a couple files from the local filesystem into the zip. All of this works fine up until I start adding larger files to the zip. I tried adding a single 43MB file, but it immediately trows a fatal error ("Allowed Memory size exhausted").

Any idea what we might be doing wrong?

**Comment by frankdejonge** [comment]
@remipelhate Hi, I've looked into this, but it seems like PHP in general is pretty bad at handling this :/ best chance would be to offload it to cli commands you'd invoke through something like `exec`, which is a bit sketchy but given your use-case it might actually work out nice.

**Comment by remipelhate** [comment]
That's what I was afraid of... Alright, thanks for helping us out :)

**Comment by frankdejonge** [comment]
No worries 👍 good luck implementing the feature!

**Comment by remipelhate** [comment]
Just so you know, we managed to solve it by using `tar` through `symfony/process`. Works like a charm. Thanks for the tip!

**Comment by frankdejonge** [comment]
Cool!
