### ISSUE TITLE
How to open zip file with password

### ISSUE THREAD

**Issue by Tilotiti** [thephpleague/flysystem-ziparchive#15]
Hi !

I would love to use this package to open my Zip archive, but it's protected by a password.

I can i open it then ?

Thank you then :)

**Comment by RoccoHoward** [comment]
@Tilotiti 

Don't know if you managed to sort this.

The primary issue is how this adapter works, every action does a ```reopenArchive```.

To get around this, you need to call the methods in the underlying ZipArchive directly - 

Instead of
```
$contents = $zip->read($path);
```

eg in Laravel:
```
$zip->getAdapter()
            ->getArchive()
            ->setPassword('password');

        $contents = $zip->getAdapter()->getArchive()->getFromName($path);
```

**Comment by Tilotiti** [comment]
Thank you for this help !
I used a different solution but I hope this answer to this problem could help other people :)
