### ISSUE TITLE
Zip only saves when object destroyed

### ISSUE THREAD

**Issue by doppynl** [thephpleague/flysystem-ziparchive#2]
When working with the Zip adapter, the changes I make to the zip are only saved once the ZipAdapter object is destroyed.

Is there a way to write the changes to disk on request? Without destroying the object.

There is a method "reopenArchive" in the Zip adapter, but it is protected.
Also, it is obviously not on the AdapterInterface as most other adapters will make the changes instantly

Perhaps something of a method "flushChanges" can be added on the Filesystem class that in turn will call the adapter telling it to "flushChanges" if that might be needed.
This will be a bit weird for other adapters that apply changes instantly though.

**Comment by danharper** [comment]
Just been bit by this today.

We ended up calling `unset` on the object to force a write.

**Comment by frankdejonge** [comment]
@doppynl unfortunately, this is how the PHP implementation of ZipArchive works. Unsetting the filesystem as @danharper suggested is the way to go.

**Comment by jasonvarga** [comment]
Would it be possible to add a more in-depth example of how to create and save a zip in the readme?

**Comment by alexw23** [comment]
👍 on this one.
