### ISSUE TITLE
No warning if zip file doesn't exist

### ISSUE THREAD

**Issue by pies** [thephpleague/flysystem-ziparchive#7]
```php
error_reporting(E_ALL);

$fs = new Filesystem(
    new ZipArchiveAdapter('/path/that/doesnt/exist.zip')
);

print_r($fs->listContents()); // prints "Array()"
```

There should be an exception.

**Comment by frankdejonge** [comment]
@pies the adapter can also be used to create zips which is a primary use-case. Check to prevent this should can easily be supplied outside of flysystem.
